---
- name: This is a hello-world example
  hosts: all
  # skip_list:
  # - 'fqcn-builtins'

  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello-world
        dest: /tmp/testfile.txt
        line: "[[ -s ${pythonbrew.bashrc_path} ]] && source ${pythonbrew.bashrc_path}"
        regexp: "^\[\[ -s \\$HOME/\.pythonbrew"
        owner: foo
        state: present
        insertafter: EOF
        create: True