# - hosts: all
#   become: true
  
#   tasks:
#     - name: Update apt cache
#       apt:
#         update_cache: yes
#       when: ansible_pkg_mgr == 'apt'
      
#     - name: Install Python
#       apt:
#         name:
#           - python3
#           - python3-pip
#         state: latest
#       when: ansible_pkg_mgr == 'apt'
      
#     - name: Install Python
#       yum:
#         name:
#           - python3
#           - python3-pip
#         state: latest
#       # when: ansible_pkg_mgr == 'yum'
---
- name: Install Python on Ubuntu
  hosts: your_host
  become: true
  tasks:
    - name: Install Python
      apt:
        name: python
        state: present