
name: MyWorkflow
on:
  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: self-hosted

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@main
        # optional:
        with:
          inventory: "inventory.yml"
          playbook: "playbook.yml"
        #   path: "playbooks/"  # <-- only one value is allowed